//	Code generated by svelte-dtsgen, version 1.0.0. DO NOT EDIT.
//	source: Button.svelte

import type { SvelteComponentTyped } from "svelte/internal";

export interface ButtonSvelteProps {}

export interface ButtonSvelteEvents {
	change?: WindowEventMap["change"];
}

export interface ButtonSvelteSlots {}

declare class ButtonSvelteComponent extends SvelteComponentTyped<ButtonSvelteProps, ButtonSvelteEvents, ButtonSvelteSlots> {
}
export default ButtonSvelteComponent;