//	Code generated by svelte-dtsgen, version 1.0.0. DO NOT EDIT.
//	source: Button.svelte

import type { SvelteComponentTyped } from "svelte/internal";

export interface ButtonSvelteProps {
	name: ?string;
	type: ?string;
	disabled: ?boolean;
}

export interface ButtonSvelteEvents {
	name: ?string;
	type: ?string;
	disabled: ?boolean;
}

export interface ButtonSvelteSlots {
	name: ?string;
	type: ?string;
	disabled: ?boolean;
}

declare class ButtonSvelteComponent extends SvelteComponentTyped<ButtonSvelteProps, ButtonSvelteEvents, ButtonSvelteSlots> {
}
export default ButtonSvelteComponent;